// Code generated by "stringer -type=Enum"; DO NOT EDIT.

package privilegecode

import "strconv"

const _Enum_name = "LoginManageAccessEditLanguageAttributesAcceptOrDeclineChangeRequests"

var _Enum_index = [...]uint8{0, 5, 17, 39, 68}

func (i Enum) String() string {
	i -= 1
	if i < 0 || i >= Enum(len(_Enum_index)-1) {
		return "Enum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Enum_name[_Enum_index[i]:_Enum_index[i+1]]
}
